# Generated by Django 5.2.12 on 2026-03-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='users',
            new_name='user',
        ),
    ]
