# Generated by Django 5.2.12 on 2026-04-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=100),
        ),
    ]
